apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soc2start.fullname" . }}-chrome
  labels:
    {{- include "soc2start.labels" . | nindent 4 }}
    app.kubernetes.io/component: chrome
spec:
  replicas: {{ .Values.chrome.replicaCount }}
  selector:
    matchLabels:
      {{- include "soc2start.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chrome
  template:
    metadata:
      labels:
        {{- include "soc2start.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chrome
    spec:
      containers:
        - name: chrome
          image: "{{ .Values.chrome.image.repository }}:{{ .Values.chrome.image.tag }}"
          imagePullPolicy: {{ .Values.chrome.image.pullPolicy }}
          args:
            - --headless
            - --disable-gpu
            - --disable-dev-shm-usage
            - --hide-scrollbars
            - --mute-audio
            - --no-default-browser-check
            - --no-first-run
            - --disable-background-networking
            - --disable-background-timer-throttling
            - --disable-extensions
          ports:
            - name: devtools
              containerPort: {{ .Values.chrome.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.chrome.resources | nindent 12 }}
