{{- if not .Values.probo.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soc2start.fullname" . }}-probo
  labels:
    {{- include "soc2start.labels" . | nindent 4 }}
type: Opaque
stringData:
  PROBOD_ENCRYPTION_KEY: {{ .Values.probo.secrets.encryptionKey | quote }}
  AUTH_COOKIE_SECRET: {{ .Values.probo.secrets.cookieSecret | quote }}
  AUTH_PASSWORD_PEPPER: {{ .Values.probo.secrets.passwordPepper | quote }}
  OAUTH2_SERVER_SIGNING_KEY: {{ .Values.probo.secrets.oauth2SigningKey | quote }}
{{- end }}
