package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// Organization is the resolver for the organization field.
func (r *deviceResolver) Organization(ctx context.Context, obj *types.Device) (*types.Organization, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionOrganizationGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	organization, err := loaders.Organization.Load(ctx, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get device organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// Owner is the resolver for the owner field.
func (r *deviceResolver) Owner(ctx context.Context, obj *types.Device) (*types.Profile, error) {
	if obj.Owner == nil {
		return nil, nil
	}

	loaders := dataloader.FromContext(ctx)

	profile, err := loaders.Profile.Load(ctx, obj.Owner.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, nil
		}

		r.logger.ErrorCtx(ctx, "cannot load device owner", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewProfile(profile), nil
}

// PostureChecks is the resolver for the postureChecks field.
func (r *deviceResolver) PostureChecks(ctx context.Context, obj *types.Device) ([]*types.DevicePostureCheck, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionDeviceGet); err != nil {
		return nil, err
	}

	checks, err := r.probo.Devices.GetPostureChecks(ctx, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot get device posture checks", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	result := make([]*types.DevicePostureCheck, len(checks))
	for i, c := range checks {
		evidence, _ := json.Marshal(c.Evidence)

		result[i] = &types.DevicePostureCheck{
			ID:         c.ID,
			CheckKey:   c.CheckKey,
			Status:     c.Status,
			Evidence:   string(evidence),
			ObservedAt: c.ObservedAt,
		}
	}

	return result, nil
}

// PostureSummary is the resolver for the postureSummary field.
func (r *deviceResolver) PostureSummary(ctx context.Context, obj *types.Device) (*types.DevicePostureSummary, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionDeviceGet); err != nil {
		return nil, err
	}

	checks, err := r.probo.Devices.GetPostureChecks(ctx, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot get device posture checks for summary", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	summary := &types.DevicePostureSummary{
		Total: len(checks),
	}

	for _, c := range checks {
		switch c.Status {
		case coredata.PostureCheckStatusPass:
			summary.Pass++
		case coredata.PostureCheckStatusFail:
			summary.Fail++
		default:
			summary.Unknown++
		}
	}

	return summary, nil
}

// Permission is the resolver for the permission field.
func (r *deviceResolver) Permission(ctx context.Context, obj *types.Device, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *deviceConnectionResolver) TotalCount(ctx context.Context, obj *types.DeviceConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionDeviceList)
	if err != nil {
		return 0, err
	}

	var status *coredata.DeviceStatus
	if obj.Filter != nil {
		status = obj.Filter.Status
	}

	deviceFilter := coredata.NewDeviceFilter(status, nil)

	count, err := r.probo.Devices.CountForOrganizationID(ctx, scope, obj.ParentID, deviceFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count devices", log.Error(err))
		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// GenerateDeviceEnrollmentToken is the resolver for the generateDeviceEnrollmentToken field.
func (r *mutationResolver) GenerateDeviceEnrollmentToken(ctx context.Context, input types.GenerateDeviceEnrollmentTokenInput) (*types.GenerateDeviceEnrollmentTokenPayload, error) {
	if _, err := r.authorize(ctx, input.OrganizationID, probo.ActionDeviceCreate); err != nil {
		return nil, err
	}

	identity := authn.IdentityFromContext(ctx)

	token, err := r.probo.Devices.GenerateEnrollmentToken(input.OrganizationID, identity.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot generate enrollment token", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.GenerateDeviceEnrollmentTokenPayload{
		EnrollmentToken: token,
	}, nil
}

// DeleteDevice is the resolver for the deleteDevice field.
func (r *mutationResolver) DeleteDevice(ctx context.Context, input types.DeleteDeviceInput) (*types.DeleteDevicePayload, error) {
	scope, err := r.authorize(ctx, input.DeviceID, probo.ActionDeviceDelete)
	if err != nil {
		return nil, err
	}

	err = r.probo.Devices.Delete(ctx, scope, input.DeviceID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete device", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteDevicePayload{
		DeletedDeviceID: input.DeviceID,
	}, nil
}

// Device returns schema.DeviceResolver implementation.
func (r *Resolver) Device() schema.DeviceResolver { return &deviceResolver{r} }

// DeviceConnection returns schema.DeviceConnectionResolver implementation.
func (r *Resolver) DeviceConnection() schema.DeviceConnectionResolver {
	return &deviceConnectionResolver{r}
}

type deviceResolver struct{ *Resolver }
type deviceConnectionResolver struct{ *Resolver }
