package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// Organization is the resolver for the organization field.
func (r *monitoringReportResolver) Organization(ctx context.Context, obj *types.MonitoringReport) (*types.Organization, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionOrganizationGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	organization, err := loaders.Organization.Load(ctx, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get monitoring report organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// File is the resolver for the file field.
func (r *monitoringReportResolver) File(ctx context.Context, obj *types.MonitoringReport) (*types.File, error) {
	if obj.File == nil {
		return nil, nil
	}

	if _, err := r.authorize(ctx, obj.ID, probo.ActionFileGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	file, err := loaders.File.Load(ctx, obj.File.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot load monitoring report file", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewFile(file), nil
}

// Uploader is the resolver for the uploader field.
func (r *monitoringReportResolver) Uploader(ctx context.Context, obj *types.MonitoringReport) (*types.Profile, error) {
	if obj.Uploader == nil {
		return nil, nil
	}

	loaders := dataloader.FromContext(ctx)

	profile, err := loaders.Profile.Load(ctx, obj.Uploader.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, nil
		}

		r.logger.ErrorCtx(ctx, "cannot load monitoring report uploader", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewProfile(profile), nil
}

// Permission is the resolver for the permission field.
func (r *monitoringReportResolver) Permission(ctx context.Context, obj *types.MonitoringReport, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *monitoringReportConnectionResolver) TotalCount(ctx context.Context, obj *types.MonitoringReportConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionMonitoringReportList)
	if err != nil {
		return 0, err
	}

	var reportType *coredata.MonitoringReportType
	if obj.Filter != nil {
		reportType = obj.Filter.ReportType
	}

	reportFilter := coredata.NewMonitoringReportFilter(reportType)

	count, err := r.probo.MonitoringReports.CountForOrganizationID(ctx, scope, obj.ParentID, reportFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count monitoring reports", log.Error(err))
		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// CreateMonitoringReport is the resolver for the createMonitoringReport field.
func (r *mutationResolver) CreateMonitoringReport(ctx context.Context, input types.CreateMonitoringReportInput) (*types.CreateMonitoringReportPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionMonitoringReportCreate)
	if err != nil {
		return nil, err
	}

	identity := authn.IdentityFromContext(ctx)
	uploaderID := identity.ID

	report, err := r.probo.MonitoringReports.Create(
		ctx,
		scope,
		input.OrganizationID,
		input.ReportType,
		input.Name,
		&uploaderID,
		&probo.FileUpload{
			Content:     input.File.File,
			Filename:    input.File.Filename,
			Size:        input.File.Size,
			ContentType: input.File.ContentType,
		},
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot create monitoring report", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateMonitoringReportPayload{
		MonitoringReportEdge: types.NewMonitoringReportEdge(report, coredata.MonitoringReportOrderFieldCreatedAt),
	}, nil
}

// DeleteMonitoringReport is the resolver for the deleteMonitoringReport field.
func (r *mutationResolver) DeleteMonitoringReport(ctx context.Context, input types.DeleteMonitoringReportInput) (*types.DeleteMonitoringReportPayload, error) {
	scope, err := r.authorize(ctx, input.MonitoringReportID, probo.ActionMonitoringReportDelete)
	if err != nil {
		return nil, err
	}

	err = r.probo.MonitoringReports.Delete(ctx, scope, input.MonitoringReportID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete monitoring report", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteMonitoringReportPayload{
		DeletedMonitoringReportID: input.MonitoringReportID,
	}, nil
}

// MonitoringReports is the resolver for the monitoringReports field.
func (r *organizationResolver) MonitoringReports(ctx context.Context, obj *types.Organization, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.MonitoringReportOrder, filter *types.MonitoringReportFilter) (*types.MonitoringReportConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionMonitoringReportList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.MonitoringReportOrderField]{
		Field:     coredata.MonitoringReportOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.MonitoringReportOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	var reportType *coredata.MonitoringReportType
	if filter != nil {
		reportType = filter.ReportType
	}

	reportFilter := coredata.NewMonitoringReportFilter(reportType)

	p, err := r.probo.MonitoringReports.ListForOrganizationID(ctx, scope, obj.ID, cursor, reportFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list monitoring reports", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewMonitoringReportConnection(p, r, obj.ID, filter), nil
}

// MonitoringReport returns schema.MonitoringReportResolver implementation.
func (r *Resolver) MonitoringReport() schema.MonitoringReportResolver {
	return &monitoringReportResolver{r}
}

// MonitoringReportConnection returns schema.MonitoringReportConnectionResolver implementation.
func (r *Resolver) MonitoringReportConnection() schema.MonitoringReportConnectionResolver {
	return &monitoringReportConnectionResolver{r}
}

type monitoringReportResolver struct{ *Resolver }
type monitoringReportConnectionResolver struct{ *Resolver }
