package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// UpdateUserColumnPreferences is the resolver for the updateUserColumnPreferences field.
func (r *mutationResolver) UpdateUserColumnPreferences(ctx context.Context, input types.UpdateUserColumnPreferencesInput) (*types.UpdateUserColumnPreferencesPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionMonitoringReportList)
	if err != nil {
		return nil, err
	}

	identity := authn.IdentityFromContext(ctx)

	pref, err := r.probo.UserColumnPreferences.Upsert(
		ctx,
		scope,
		identity.ID,
		input.ReportType,
		input.SelectedColumns,
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot upsert user column preferences", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateUserColumnPreferencesPayload{
		UserColumnPreference: types.NewUserColumnPreference(pref),
	}, nil
}
